pharmacy_site/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from users import views as users_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('shop/', include('shop.urls')),
    path('', include('main_site.urls')),
    path('articles/', include('articles.urls')),
    path('register/', users_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
    name='password_reset'),
    path('password-reset/done', 
    auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
    name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
    name='password_reset_confirm'),
    path('password-reset-complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
    name='password_reset_complete'),
    path('profile/', users_views.profile, name='profile'),
    path('cart/', users_views.cart, name='cart'),
    path('checkout/', users_views.checkout, name='checkout'),
    path('update_item/', users_views.updateItem, name='update_item'),
    path('process_order/', users_views.processOrder, name='process_order'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import (
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('new/', ProductCreateView.as_view(), name='product-create'),
    path('<int:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('<int:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import (
    ShopHomeView,
    ShopFluView,
    ShopHeartView,
    ShopEyeGlassesView,
    ShopEyeMedsView,
    ShopBrandView,
)

urlpatterns = [
    path('', ShopHomeView.as_view(), name='shop-home'),
    path('shop-flu', ShopFluView.as_view(), name='shop-flu'),
    path('shop-eye-glasses', ShopEyeGlassesView.as_view(), name='shop-eye-glasses'),
    path('shop-eye-medicine', ShopEyeMedsView.as_view(), name='shop-eye-medicine'),
    path('shop-heart', ShopHeartView.as_view(), name='shop-heart'),
    path('shop-brand/<str:brand_id>', ShopBrandView.as_view(), name='shop-brand'),
    ]

products/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
import decimal
import os
from PIL import Image

PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]

base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
product_image_dir = base_dir + '\media\product_pics'

product_categories = (
    ('flu', 'Flu medicine'),
    ('eye_glasses', 'Eye glasses'),
    ('eye_medicine', 'Eye medicine'),
    ('heart', 'Heart medicine'),
)

brands = (
    ('choose_brand', ''),
    ('brand_1', 'Brand 1'),
    ('brand_2', 'Brand 2'),
    ('brand_3', 'Brand 3'),
    ('brand_4', 'Brand 4'),
    ('brand_5', 'Brand 5'),
)

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discount_percent = models.IntegerField(default=0, validators=PERCENTAGE_VALIDATOR, blank=True)
    discounted_price = models.DecimalField(max_digits=6, decimal_places=2, blank=True)
    picture = models.ImageField(blank=True, upload_to=product_image_dir)
    number_in_stock = models.IntegerField(default=0)
    category = models.CharField(max_length=100, choices=product_categories, default='flu')
    brand = models.CharField(max_length=100, choices=brands, default='choose_brand')
    

    @property
    def get_price_with_discount(self):
        return decimal.Decimal(self.price) - decimal.Decimal(self.price)*decimal.Decimal((decimal.Decimal(self.discount_percent)/100))

    def save(self, *args, **kwargs):
        self.discounted_price = self.get_price_with_discount
        super(Product, self).save(*args, **kwargs)
        try:
            img = Image.open(self.picture.path)

            if img.height > 200 or img.width > 320:
                output_size = (320, 200)
                img.thumbnail(output_size)
                img.save(self.picture.path)
        except ValueError:
            pass

    def __str__(self):
        return f'{self.title}'

products/views.py
# from django.shortcuts import render
# from django.http import HttpResponse
# from .models import Product

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from .models import Product
from django.views.generic import (
    DetailView, 
    CreateView,
    UpdateView,
    DeleteView
    )

class ProductDetailView(DetailView):
    model = Product

class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    fields = [
        'title', 
        'description', 
        'price', 
        'discount_percent', 
        'picture', 
        'number_in_stock', 
        'category', 
        'brand'
        ]

    def get_success_url(self):
        return reverse('product-detail', kwargs={'pk': self.object.id})

    def test_func(self):
        product = self.get_object()
        if (self.request.user.profile.user_rights == 'admin') or (self.request.user.profile.user_rights == 'employee'):
            return True
        return False

class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    fields = [
        'title', 
        'description', 
        'price', 
        'discount_percent', 
        'picture', 
        'number_in_stock', 
        'category', 
        'brand'
        ]

    def get_success_url(self):
        return reverse('product-detail', kwargs={'pk': self.object.id})

    def test_func(self):
        product = self.get_object()
        if (self.request.user.profile.user_rights == 'admin') or (self.request.user.profile.user_rights == 'employee'):
            return True
        return False

class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product

    def get_success_url(self):
        return reverse('shop-home')

    def test_func(self):
        product = self.get_object()
        if (self.request.user.profile.user_rights == 'admin') or (self.request.user.profile.user_rights == 'employee'):
            return True
        return False

products/templates/products/product_confirm_delete.html
{% extends "main_site/main-site-base.html" %}
{% block title %} <title>Delete product</title> {% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group" style="max-width: 50%">
                <legend class="border-bottom mb-4">Delete Product</legend>
            </fieldset>
            <h2>Are you sure you want to delete the product "{{ object.title }}"?</h2>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'product-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "products/products-base.html" %}
{% block content %}

<head>
  <title>Product</title>
</head>
<body>
    
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <ul class="list-group shadow">
                <li class="list-group-item">
                    <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                        <div class="media-body order-2 order-lg-1">
                            <h5 class="mt-0 font-weight-bold mb-2">
                              {{object.title}}
                              {% if user.profile.user_rights == 'admin' or user.profile.user_rights == 'employee' %}
                              <a href="{% url 'product-delete' object.id %}">
                                <button class="btn btn-primary float-end button" href="#" role="button" id="cart_btn">Delete product</button>
                              </a>
                              <a href="{% url 'product-update' object.id %}">
                                <button class="btn btn-primary float-end button" href="#" role="button" id="cart_btn">Update product</button>
                              </a>
                              <p>Number in stock: {{object.number_in_stock}}</p>
                            {% endif %}
                            </h5>
                            <br>
                            <h6>{{object.get_category_display}}</h6>
                            {% if object.get_brand_display != '' %} 
                              <h6><a class="mr-2" href="{% url 'shop-brand' object.brand %}">{{product.get_brand_display}}</a></h6>
                            {% else %}
                              <br>
                            {% endif %}
                            {% if object.picture %}
                                <img src={{object.picture.url}} alt="product placeholder image" width="200" class="ml-lg-5 order-1 order-lg-2">
                            {% endif %}
                            
                            <div class="d-flex align-items-center justify-content-between mt-1">
                                <h6 class="font-weight-bold my-2">{% if object.price > object.discounted_price %} 
                                    <del>{{object.price}}</del> <ins style="color:red">{{object.discounted_price}}</ins>
                                    {% else %}
                                        {{object.price}}
                                    {% endif %}
                                </h6>
                            </div>
                        </div>
                        
                        {% if object.number_in_stock == 0 %}
                          <p>Out of stock</p>
                        {% else %}
                          <form method="POST">
                            <input type="number" step="1" min="0" max="{{object.number_in_stock}}" value="0" name="medicine_qty" class="quantity-field">
                            <button class="btn btn-outline-primary add" type="submit">Add To Cart</button>
                          </form>
                        {% endif %}
                        
                        <p>
                            {{object.description}}
                        </p>
                        
                    </div>
                </li>
            </ul>
        </div>
        
    </div>
</body>
{% endblock %}

products/templates/products/product_form.html
{% extends "main_site/main-site-base.html" %}
{% block title %} <title>Add new product</title> {% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group" style="max-width: 50%">
                <legend class="border-bottom mb-4">Product</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Post</button>
                {% if object.id %}
                    <a class="btn btn-outline-secondary" href="{% url 'product-detail' object.id %}">Cancel</a>
                {% else %}
                    <a class="btn btn-outline-secondary" href="{% url 'shop-home' %}">Cancel</a>
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

products/templates/products/products-base.html
{% extends "main_site/main-site-base.html" %}
{% block title %} {% endblock %}

products/templates/products/products-home.html
{% extends "products/products-base.html" %}
{% block content %}

<head>
  <title>Product</title>
</head>
<body>
    {% for product in products %}
    
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <ul class="list-group shadow">
                <li class="list-group-item">
                    <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                        <div class="media-body order-2 order-lg-1">
                          
                            <p class="mt-0 font-weight-bold mb-2">{{product.title}}</p>
                            {% if product.get_brand_display != '' %} 
                              <form method="POST" action="{% url 'shop-brand' %}" name="brand_search_form">
                                {% csrf_token %}  
                                <button 
                                  type="submit"
                                  class="btn btn-link"
                                  name="brand_search" 
                                  value="{{product.brand}}">
                                  {{product.get_brand_display}}
                                </button>
                              </form>
                            {% else %}
                              <br>
                            {% endif %}
                            {% if product.picture %}
                                <img src={{product.picture.url}} alt="product placeholder image" width="200" class="ml-lg-5 order-1 order-lg-2">
                            {% endif %}
                            
                            <div class="d-flex align-items-center justify-content-between mt-1">
                                <h6 class="font-weight-bold my-2">{% if product.price > product.discounted_price %} 
                                    <del>{{product.price}}</del> <ins style="color:red">{{product.discounted_price}}</ins>
                                    {% else %}
                                        {{product.price}}
                                    {% endif %}
                                </h6>
                            </div>
                        </div>
                        
                        {% if product.number_in_stock == 0 %}
                          <p>Out of stock</p>
                        {% else %}
                          <form method="POST">
                            <input type="number" step="1" min="0" max="{{product.number_in_stock}}" value="0" name="medicine_qty" class="quantity-field">
                            <button class="btn btn-outline-primary add" type="submit">Add To Cart</button>
                          </form>
                        {% endif %}
                        
                        <p>
                            {{product.description}}
                        </p>
                        
                    </div>
                </li>
            </ul>
        </div>
        
    </div>
{% endfor %}
    </body>
{% endblock %}